services:
  - type: web
    name: aero-price-production-team
    runtime: static
    branch: main
    autoDeploy: true
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
